controllers:
    resource: ../../src/Controller/Api
    type: annotation
    prefix: /api
    name_prefix: api_
    trailing_slash_on_root: false

kernel:
    resource: ../../src/Kernel.php
    type: annotation
